# Site
name: 'Xpat World'
description: 'Xpat World brings you affodable tech solutions and free downloads.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'xpatworld'
email: 'xpatworld2021@gmail.com'
mailchimp-list: 'https://xpatworld.us20.list-manage.com/subscribe/post?u=fea5d468a51e549bfe9fb954d&amp;id=f79b2bce42'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           DJ X-PAT 254
      site:           https://www.xpatworld.ml
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am DJ X-PAT 254, the author of Xpat World, the site you're currently on. I hope you like it!"
      email:          xpatworld2021@gmail.com
      twitter:        https://twitter.com/djxpat254

    jane:
      name:           DJ X-PAT 254
      site:           https://www.xpatworld.ml
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          xpatworld2021@gmail.com
      twitter:        https://twitter.com/djxpat254
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
